### ISSUE TITLE
Wishlist: a set_level() method [rt.cpan.org #64479]

### ISSUE THREAD

**Issue by dagolden** [dagolden/Log-Any#14]
https://rt.cpan.org/Ticket/Display.html?id=64479

    I'd be happy to contribute the code myself for this - I'll even accept co-maint and do the release 
    work if it makes the decision easier!
    
    Basically, I feel that since Log::Any adaptors are already more or less aware of logging levels, the 
    interface for Log::Any should also specify a standard method for setting the log level (which the 
    adaptors would then implement)
    
    Let me know what you think, especially if there's a good reason to *not* do so!

**Comment by dagolden** [comment]
Excerpt of my response from there:
>If you mean that there should be an API to tell Adapters (the log message consumers) to change the level on the loggers they manage, that might be feasible, but isn't backwards compatible -- existing Adapters won't support it, so there's a migration issue.

**Comment by TiMBuS** [comment]
Hello, I would like to bump, or '+1' this in some way. 

I have broken a rather massive project up into a bunch of smaller private CPAN-ish packages, and in doing so switched I from Log4perl to Log::Any so that the modules can work without worrying about the running application's logger setup. 
All was well until we realized it's no longer possible to dynamically set log levels on the command line (with -v and -q). Log4perl let me set more_logging and less_logging on the shared logger instance.

My only solution at the moment seems to be to edit the Log4perl config when the application loads, which seems .. bad.

Log::Any::App seems to set the levels, but I can't seem to feed it the app's log4perl.conf.

Kinda frustrating =[

**Comment by nrdvana** [comment]
@TiMBuS I think the proper solution to your problem is for the top-level script to be fully aware of Log4perl and use it's APIs.  The purpose of Log::Any is to disconnect the producers of log info from the consumers of log info.  The producer of log info shouldn't ever have an opinion of how to set the log level.

If you frequently need to do the same logging setup in multiple scripts, then consider wrapping that in your own library.  i.e. a library which parses ARGV, ENV, and calls Log4perl functions.

**Comment by xdg** [comment]
The `filter` option allows proxy-side filtering based on level.  Given that feature, I'm going to close this ticket.  Here's an example filter function:

```perl
use Log::Any::Adapter::Util ':levels';
$filter_fcn = sub {
    my ($cat, $lvl, $msg) = @_;
    return $lvl <= ERROR ? $msg : undef;
}
```

**Comment by nrdvana** [comment]
@TiMBuS you might also be interested in my recently rewritten adapter Log::Any::Adapter::Daemontools, which can even change log levels on the fly.  It only logs to a single file handle though.
