### ISSUE TITLE
Incorrectly stringifies hashrefs

### ISSUE THREAD

**Issue by PopeFelix** [dagolden/Log-Any#34]
```perl
$self->log->info( { key => 12345, client => 'A Client', message => 'Something' } )
```
This will be stringified into 'HASH(0x12345678)', when I would expect it to be passed as is.

This happens at Log/Any/Proxy.pm, line 67:

```perl
my $message = join(" ", grep { defined($_) && length($_) } @parts );
```

A potential fix might be:
```perl
# Insert before line 67
my $concat = 1;
for my $part (@parts) {
    if (ref $part eq 'ARRAY' || ref $part eq 'HASH') {
      $concat = 0;
      last;
   }
}
return $self->{adapter}->$realname($parts[0]) if !$concat && $parts[0];
# Line 67 on as usual
```

**Comment by xdg** [comment]
The basic logging methods only take strings.  They are not passed through to the adapters because not all adapters handle things other than strings.  The Log::Any API is the lowest-common denominator of logging capabilities.

You can achieve what you want with the formatting functions (`infof("%s", $hashef)`), or you could define your own formattter.
